services:
  jsoncrack:
    image: jsoncrack
    container_name: jsoncrack
    restart: on-failure
    user: nginx
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - NODE_ENV=production