name: Bug report
description: Create a report to help us improve
title: "[BUG]: <Context of the issue>"
labels: bug
assignees: AykutSarac
body:
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with below code sample:
        1. do thing
        2. click...
        3. observe behavior
        4. see error logs below
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Media & Screenshots
      description: Inlude screenshots or video of reproduction as much as possible
      render: md
  - type: textarea
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?
      value: |
       - OS: [e.g. iOS]:
       - Browser [e.g. chrome, safari]:
       
       - Any other details...
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
