# run one worker per cpu core
worker_processes auto;

events {
  # cap max connections
  worker_connections 8192;
}

http {
  # disable logging so we dont need so much disk space
  access_log off;

  # set docker dns so we can reslove hostnames like "web"
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;

    location / {
      # use the $backend variable so that nginx not uses the same web instance for all requests
      set $backend "http://web:8080";
      proxy_pass $backend;

      # forward the original client details so it not looks like nginx is making all requests
      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}